[package]
name = "gdtk-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdtk-lexer = { version = "0.1.0", path = "../gdtk-lexer" }
gdtk-ast = { version = "0.1.0", path = "../gdtk-ast" }
error-stack = "0.3.1"
thiserror = "1.0.43"
