version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "07:00"
    reviewers:
      - "elenakrittik"
    commit-message:
      prefix: "deps"
    labels:
      - "a: deps"
