[package]
name = "gdtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.11", features = ["derive"] }
colored = "2.0.0"
pest = "2.5.6"
pest_derive = "2.5.6"
