[package]
name = "gdtk-gdscript-trustfall-adapter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-as-inner = "0.6.0"
trustfall = "0.7.1"
gdtk-ast = { path = "../gdtk-ast", version = "0.1.0" }
