[package]
name = "gdtk-lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-stack = "0.4.0"
logos = "0.13.0"
thiserror = "1.0.43"
