[package]
name = "gdtk-gdscript-ast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdtk-span = { path = "../gdtk-span", version = "0.1.0" }
enum-as-inner = "0.6.0"
derivative = "2.2.0"
