[package]
name = "gdtk-gvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.8.6", features = ["serde"] }
anyhow = "1.0.75"
dirs = "5.0.1"
gdtk-macros = { version = "0.1.0", path = "../gdtk-macros" }
gdtk-utils = { version = "0.1.0", path = "../gdtk-utils" }
reqwest = { version = "0.12.1", features = ["json"] }
thiserror = "1.0.50"
bytes = "1.5.0"
toml = "0.8.6"
versions = "6.0.0"
xxhash-rust = { version = "0.8.7", features = ["xxh3"] }
scraper = "0.19.0"
rayon = "1.8.0"
futures = "0.3.29"
serde = { version = "1.0.192", features = ["derive"] }
tokio = "1.34.0"
url = "2.4.1"
serde_json = "1.0.114"
extend = "1.2.0"
tabled = "0.15.0"
