[package]
name = "gdtk-gvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = { version = "0.8.6", features = ["serde"] }
gdtk-paths = { version = "0.1.0", path = "../gdtk-paths" }
serde = { version = "1.0.203", features = ["derive"] }
reqwest = "0.12.5"
thiserror = "1.0.61"
toml = "0.8.14"
versions = "6.0.0"
scraper = "0.19.0"
url = "2.5.1"
tabled = "0.15.0"
