[package]
name = "diagnosis"
version = "0.1.0"
edition = "2021"

[dependencies]
yansi = { version = "1.0.1", features = ["hyperlink"], optional = true }
thiserror = { version = "1.0", optional = true }

[features]
rustc = ["dep:yansi", "dep:thiserror"]
