[package]
name = "gdtk-lint"
version = "0.1.0"
edition = "2021"

[dependencies]
heck = "0.5.0"
miette = "7.2.0"
gdtk-ast = { version = "0.1.0", path = "../gdtk-ast" }
gdtk-macros = { version = "0.1.0", path = "../gdtk-macros" }
gdtk-span = { path = "../gdtk-span", version = "0.1.0" }
