[package]
name = "gdtk-lint"
version = "0.1.0"
edition = "2021"

[dependencies]
heck = "0.5.0"
gdtk-ast = { version = "0.1.0", path = "../gdtk-ast" }
gdtk-diag = { version = "0.1.0", path = "../gdtk-diag" }
