[package]
name = "gdtk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
ariadne = "0.3.0"
clap = { version = "4.3.11", features = ["derive"] }
comfy-table = "7.1.0"
gdtk-gvm = { version = "0.1.0", path = "../gdtk-gvm" }
gdtk-lexer = { version = "0.1.0", path = "../gdtk-lexer" }
gdtk-parser = { version = "0.1.0", path = "../gdtk-parser" }
gdtk-utils = { version = "0.1.0", path = "../gdtk-utils" }
lazy_static = "1.4.0"
owo-colors = "3.5.0"
thiserror = "1.0.40"
tokio = { version = "1.34.0", features = ["full"] }

[lib]
name = "gdtk"
