[package]
name = "gdtk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
ariadne = "0.4.0"
clap = { version = "4.3.11", features = ["derive"] }
comfy-table = "7.1.0"
gdtk-gvm = { version = "0.1.0", path = "../gdtk-gvm" }
gdtk-lexer = { version = "0.1.0", path = "../gdtk-lexer" }
gdtk-parser = { version = "0.1.0", path = "../gdtk-parser" }
gdtk-utils = { version = "0.1.0", path = "../gdtk-utils" }
lazy_static = "1.4.0"
owo-colors = "4.0.0"
thiserror = "1.0.40"
tokio = { version = "1.34.0", features = ["full"] }
zip-extract = { version = "0.1.2", default-features = false, features = ["deflate"] }
itertools = "0.12.1"
gdtk-dialoguer = { path = "../gdtk-dialoguer", version = "0.11.0", features = ["fuzzy-select"], default-features = false }
reqwest = "0.11.23"
tabled = { version = "0.15.0", features = ["std"] }

[lib]
name = "gdtk"
