name: Weekly nightly rotation.

on:
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:
  push:
    branches:
      - "*"
    paths:
      - "*"

jobs:
  update_nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly

      - name: Install ripgrep and sponge.
        run: sudo apt-get install -y ripgrep moreutils

      - name: Replace nightly versions.
        run: |
          RUSTC_VERSION='${{ steps.rust.outputs.rustc-version }}'
          NIGHTLY_REGEX='nightly-[0-9]{4}(?:-[0-9]{2}){2}'

          for workflow_file in .github/workflows/*; do
            FILENAME="./.github/workflows/$workflow_file"

            rg --passthru "$NIGHTLY_REGEX" -r "$RUSTC_VERSION" "$FILENAME" | sponge "$FILENAME"
          done

      - name: Submit changes.
        uses: peter-evans/create-pull-request@v6
        with:
          title: "deps: Automated nightly version update."
          body: ""
          commit-message: "Update nightly version."
          branch: "deps/weekly-update"
          delete-branch: true
          labels: "a: deps"
